### ISSUE TITLE
exception when command not found

### ISSUE THREAD

**Issue by fredrb** [Bashmug/betty#15]
When betty executes a program based on user input, this can result in an exception if program is not found. For example:

```
$ betty what version ajd
betty: Running ajd --version
/home/fredrb/code/ruby/betty/main.rb:106:in ``': No such file or directory - ajd (Errno::ENOENT)
    from /home/fredrb/code/ruby/betty/main.rb:106:in `run'
    from /home/fredrb/code/ruby/betty/main.rb:239:in `main'
    from /home/fredrb/code/ruby/betty/main.rb:260:in `<main>'
```

Perhaps we should show a message to the user saying that betty cannot find such program or file.

**Comment by xeon-zolt** [comment]
closing issue as it seems to be resolved
